### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by sandikata** [jimeh/.emacs.d#10]
Hello, how I can use TAB as TAB, not just as suggestion menu ?

**Comment by jimeh** [comment]
To direcly insert a TAB (`\t`) character, you can use `C-q TAB`, as `C-q` triggers `quoted-insert`, which reads the next input and inserts it.

The TAB key in my setup is bound to `company-indent-or-complete-common` which will either indent current line to the correct indentation level, or trigger company completion. If you want to use tabs for indentation, you should configure the major-mode in question to do so, or set `indent-tabs-mode` to `t` for the specific buffers/major-mode.

**Comment by sandikata** [comment]
Thank you for response, it's really nice specially for yaml. But i see some errors in loading plugins. Is it version dependent ?

File:           emacs-nox-26.3-2-x86_64.pkg.tar.zst
Version:        26.3-2

**Comment by jimeh** [comment]
Ah, for YAML I'm pretty sure you're supposed to use two spaces for indentation, which my config should be doing by default when you press TAB.

Everything specific to Emacs 27.x has fallbacks for 26.x. So there's nothing specific that locks out 26.x, but personally I've been running 27.x nightly builds for about 6 months, so I don't know if any issues have showed up with 26.x.

**Comment by sandikata** [comment]
Yep, it's really good for yaml, i need it at my workplase.

**Comment by sandikata** [comment]
![2020-08-07_1920x1036_scrot](https://user-images.githubusercontent.com/884699/89648745-5804f480-d8c8-11ea-8c88-f31b1101aeb9.png)

treemacs fails to pull.

**Comment by jimeh** [comment]
Weird, seems like it's failing to clone the commit that straight has locked treemacs too.

You can try updating it to latest treemacs commit by running `M-x straight-pull-package` and selecting `treemacs`, then `M-x straight-check-package` -> `treemacs` to build it.

Or if you want you can try and update all packages with `M-x straight-pull-all` followed by `M-x straight-check-all`.

**Comment by sandikata** [comment]
There will be one more question.
How can I copy to buffer, as this function is changed with your emacsrc ?

**Comment by sandikata** [comment]
It would be good if you add some readme with all the shortcuts and functions/features.

**Comment by jimeh** [comment]
I haven't really done anything special to the copy/paste stuff, regular system keybindings should mostly work, along with Emacs' standard killring keybindings.

Keep in mind that emacs doesn't have a "clipboard", it has a [killring](https://www.gnu.org/software/emacs/manual/html_node/emacs/Kill-Ring.html) which works differently from a normal clipboard. But it tries to keep the killring in sync with the clipboard if it can, depending on your OS and method of running emacs.

A better readme is something I've been meaning to do for some time, but very few people have been interested in my config so far, so I haven't made it a high priority... lol

**Comment by sandikata** [comment]
I like your work, and that's why i am asking for some readme with additional stuff.
