### ISSUE TITLE
yaml/ansible syntax 

### ISSUE THREAD

**Issue by sandikata** [jimeh/.emacs.d#12]
I'm facing weird behavior in yaml mode if I copy paste a formated playbook.
emacs just makes it with multiple tabs in any new line, and it's absolutely unreadable and broken code at all.
Do you have any ideas ?

**Comment by jimeh** [comment]
This behavior is what I'd expect if auto-indenting was firing for `yaml-mode`. But it's disabled for YAML and various other indentation-sensitive major modes by default. However if you've customized the [`siren-indent-sensitive-modes`](https://github.com/jimeh/.emacs.d/blob/4faa48a09b5916f283f54b2398546517bab3a634/core/siren-core-custom.el#L20-L26) variable, make sure `yaml-mode` is still listed there.

**Comment by sandikata** [comment]
Yep it's still there. Well, if you found some fix i'll be happy :)

**Comment by jimeh** [comment]
I'm afraid I can't re-produce the issue myself. Are you sure you're using `yaml-mode` major mode for the files in question, and not some other ansible specific major mode?

To check if it's the auto-indent on paste code causing the issue, try commenting out these lines locally and restart emacs: https://github.com/jimeh/.emacs.d/blob/4faa48a09b5916f283f54b2398546517bab3a634/core/siren-core-editor.el#L170-L178
