### ISSUE TITLE
emacs config complains about highlight-indent-guides

### ISSUE THREAD

**Issue by sandikata** [jimeh/.emacs.d#14]
The full message.

highlight-indent-guides cannot set faces default face is not set properly

**Comment by jimeh** [comment]
As far as I can tell that warning doesn't actually have much of any effect, as the highlight-indent-guides package still works just fine using the correct faces.

That said, I've seen that error for a while and been meaning to take a look it at some point, so I'll leave this issue open until I do.

**Comment by sandikata** [comment]
Well, thank you. Keep your good work.

**Comment by jimeh** [comment]
I forgot to address this a while ago. I believe I eventually got around to sorting oh my this error, but it was like 2 years ago, so I don't recall what it was exactly.

Also I actually stopped using indent guides maybe 1 year ago? So this error definitely shouldn't be appearing anymore, at least not by default.
