### ISSUE TITLE
Startup Error with Emacs 1da7019

### ISSUE THREAD

**Issue by robyoung26** [jimeh/.emacs.d#2]
I know you're aware of this issue, but thought I'd raise it anyway to give a little more information.

Was able to get it running by commenting out `auto-complete-emacs-lisp` related stuff around lines 127 and 161 of `packages.el`

For now, have reverted to known good 7ae7d68 as suggested :-)

**Comment by jimeh** [comment]
I'm closing this issue as it's over 6 years old.
